/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QL_Laptop;

import java.awt.CardLayout;
import java.awt.List;
import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Stream;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private ArrayList<Laptop> list;
    private DefaultTableModel model;
    //Laptop s;
    String PassWord;
    public MainFrame() throws IOException {
        initComponents();
        list=new ArrayList<>();
        model=(DefaultTableModel) jTable1.getModel();       
        readFile();
        readMatkhau();
        showData(list);
        //PassWord=readMatkhau();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Loggin = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPasswordField2 = new javax.swing.JPasswordField();
        Interface_Management = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtdongMay = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtseries = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtcpu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtram = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtoCung = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtmanHinh = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtdoPhanGiai = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtcardDoHoa = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtgia = new javax.swing.JTextField();
        jbtnhienthi = new javax.swing.JButton();
        jbtnthem = new javax.swing.JButton();
        jbtnxoa = new javax.swing.JButton();
        jbtntimkiem = new javax.swing.JButton();
        jbtthoat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txttrongluong = new javax.swing.JTextField();
        jbtnreset = new javax.swing.JButton();
        jbtnsua = new javax.swing.JButton();
        jbtndoimatkhau = new javax.swing.JButton();
        txtdoimatkhau = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QL_Laptop");
        setPreferredSize(new java.awt.Dimension(900, 682));
        getContentPane().setLayout(new java.awt.CardLayout());

        Loggin.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Mật khẩu");
        Loggin.add(jLabel5);
        jLabel5.setBounds(240, 200, 110, 50);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Đăng nhập");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Loggin.add(jButton2);
        jButton2.setBounds(320, 270, 190, 50);
        Loggin.add(jPasswordField2);
        jPasswordField2.setBounds(390, 200, 170, 40);

        getContentPane().add(Loggin, "card2");

        Interface_Management.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setForeground(new java.awt.Color(255, 153, 51));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Dòng máy", "Series", "CPU", "RAM", "Ổ cứng", "Màn hình", "Độ phân giải", "Card đồ họa", "Trọng lượng", "Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel3.setLayout(null);

        jLabel7.setText("Dòng máy");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(0, 10, 55, 16);

        txtdongMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdongMayActionPerformed(evt);
            }
        });
        jPanel3.add(txtdongMay);
        txtdongMay.setBounds(60, 0, 100, 26);

        jLabel4.setText("Series   ");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(160, 10, 50, 16);
        jPanel3.add(txtseries);
        txtseries.setBounds(250, 0, 90, 30);

        jLabel8.setText("CPU         ");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(340, 10, 60, 16);
        jPanel3.add(txtcpu);
        txtcpu.setBounds(420, 0, 80, 26);

        jLabel9.setText("RAM   ");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(520, 10, 40, 16);
        jPanel3.add(txtram);
        txtram.setBounds(570, 0, 100, 30);

        jLabel10.setText("Ổ cứng ");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(680, 10, 50, 16);
        jPanel3.add(txtoCung);
        txtoCung.setBounds(750, 0, 100, 30);

        jLabel11.setText("Màn hình  ");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(0, 40, 70, 16);
        jPanel3.add(txtmanHinh);
        txtmanHinh.setBounds(60, 26, 100, 30);

        jLabel12.setText("Độ phân giải");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(160, 40, 80, 16);

        txtdoPhanGiai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdoPhanGiaiActionPerformed(evt);
            }
        });
        jPanel3.add(txtdoPhanGiai);
        txtdoPhanGiai.setBounds(250, 30, 90, 30);

        jLabel13.setText("Card đồ họa");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(340, 40, 80, 16);
        jPanel3.add(txtcardDoHoa);
        txtcardDoHoa.setBounds(420, 26, 80, 30);

        jLabel15.setText("Giá");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(690, 40, 30, 16);
        jPanel3.add(txtgia);
        txtgia.setBounds(750, 30, 100, 30);

        jbtnhienthi.setText("Hiển thị");
        jbtnhienthi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnhienthi.setMargin(new java.awt.Insets(2, 14, 3, 30));
        jbtnhienthi.setPreferredSize(new java.awt.Dimension(60, 30));
        jbtnhienthi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnhienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnhienthiActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnhienthi);
        jbtnhienthi.setBounds(50, 80, 110, 23);

        jbtnthem.setText("Thêm ");
        jbtnthem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnthem.setMargin(new java.awt.Insets(2, 14, 3, 30));
        jbtnthem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnthemActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnthem);
        jbtnthem.setBounds(50, 120, 110, 23);

        jbtnxoa.setText("Xóa");
        jbtnxoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnxoa.setMargin(new java.awt.Insets(2, 14, 3, 30));
        jbtnxoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnxoaActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnxoa);
        jbtnxoa.setBounds(410, 80, 100, 23);

        jbtntimkiem.setText("Tìm kiếm");
        jbtntimkiem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtntimkiem.setMargin(new java.awt.Insets(2, 14, 3, 30));
        jbtntimkiem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntimkiemActionPerformed(evt);
            }
        });
        jPanel3.add(jbtntimkiem);
        jbtntimkiem.setBounds(240, 80, 110, 23);

        jbtthoat.setText("Thoát");
        jbtthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtthoatActionPerformed(evt);
            }
        });
        jPanel3.add(jbtthoat);
        jbtthoat.setBounds(410, 120, 100, 23);

        jLabel1.setText("Trọng lượng");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(510, 40, 80, 16);
        jPanel3.add(txttrongluong);
        txttrongluong.setBounds(600, 30, 71, 30);

        jbtnreset.setText("Reset");
        jbtnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnresetActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnreset);
        jbtnreset.setBounds(550, 80, 110, 23);

        jbtnsua.setText("Sửa");
        jbtnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsuaActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnsua);
        jbtnsua.setBounds(240, 120, 110, 23);

        jbtndoimatkhau.setText("Đổi mật khẩu");
        jbtndoimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndoimatkhauActionPerformed(evt);
            }
        });
        jPanel3.add(jbtndoimatkhau);
        jbtndoimatkhau.setBounds(740, 120, 110, 23);

        txtdoimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdoimatkhauActionPerformed(evt);
            }
        });
        jPanel3.add(txtdoimatkhau);
        txtdoimatkhau.setBounds(750, 80, 100, 30);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\313016481_587096799836086_417150729532915760_n.png")); // NOI18N
        jLabel2.setLabelFor(jPanel1);
        jLabel2.setText("QUẢN LÝ LAPTOP");
        jLabel2.setPreferredSize(new java.awt.Dimension(291, 130));
        jPanel1.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        Interface_Management.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(Interface_Management, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdoPhanGiaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdoPhanGiaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdoPhanGiaiActionPerformed
    
    private void jbtnhienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnhienthiActionPerformed
        // TODO add your handling code here:
       showData(list); 
    }//GEN-LAST:event_jbtnhienthiActionPerformed
    private void readMatkhau()
    {
        //char mk[];
        FileInputStream fis=null;
        BufferedInputStream bin=null;
        //ObjectInputStream ois=null; 
        try {
            fis=new FileInputStream("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\BaiTapLon_QL Laptop\\src\\QL_Laptop\\matkhau.txt");
            bin = new BufferedInputStream(fis);
            byte [] data=new byte[1024];
            int length=bin.read(data);
            PassWord=new String(data,0,length);
//            int ch;
//            while ((ch = bin.read()) != -1)
//                System.out.print((char) ch);
       
        } catch (Exception e) {
            e.printStackTrace();
        }
        finally{
            try {
                if(fis!=null)
                {
                     fis.close();
                     bin.close();
                }
                
               
            } catch (Exception e) {
                e.printStackTrace();
            }
 
        }           
    }
    private void writeMatkhau() throws IOException
    {
        FileOutputStream fos=null;
        try {
            fos=new FileOutputStream("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\BaiTapLon_QL Laptop\\src\\QL_Laptop\\matkhau.txt");
            byte b[];
            b = PassWord.getBytes();
            fos.write(b);
        } catch (Exception e) {
            e.printStackTrace();
        }
        finally{
            fos.close();
        }
    }
    private void readFile()
    {
        FileInputStream fis=null;
        ObjectInputStream ois=null; 
        try {
            fis=new FileInputStream("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\BaiTapLon_QL Laptop\\src\\QL_Laptop\\Laptop.data");
            ois=new ObjectInputStream(fis);
            list= (ArrayList<Laptop>) ois.readObject();
        } catch (Exception e) {
            e.printStackTrace();
        }
        finally{
            try {
                if(fis!=null)
                {
                     fis.close();
                }
                if (ois!=null){
                    ois.close();
                }
                
               
            } catch (Exception e) {
                e.printStackTrace();
            }
 
        }           
    }
    private void writeFile()  
    {
        FileOutputStream fos=null;
        ObjectOutputStream oos=null;
        try {
            fos= new FileOutputStream("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\BaiTapLon_QL Laptop\\src\\QL_Laptop\\Laptop.data");
            oos=new ObjectOutputStream(fos);
            oos.writeObject(list);
        } catch (Exception e) {
            e.printStackTrace();
        }
        finally{
            try {
                if (fos!=null)
                {
                    fos.close(); 
                }
                if (oos!=null)
                {
                     oos.close();
                }                           
            } catch (Exception e) {
                e.printStackTrace();
            }    
        }      
    }

    private void jbtnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnthemActionPerformed
        // TODO add your handling code here:
        String dongMay=txtdongMay.getText();
        String series=txtseries.getText();
        String cpu=txtcpu.getText();
        String ram=txtram.getText();
        String oCung=txtoCung.getText();
        String manHinh=txtmanHinh.getText();
        String gia=txtgia.getText();
        String doPhanGiai=txtdoPhanGiai.getText();
        String cardDoHoa=txtcardDoHoa.getText();
        String trongLuong=txttrongluong.getText();
        Laptop lp=new Laptop(dongMay,series,cpu,ram,oCung,manHinh,doPhanGiai,cardDoHoa,trongLuong,gia);
       
        //jTable1.setModel(new DefaultTableModel(dataLaptop,laptop));      
        
        
        if (check())
        {
             list.add(lp);
             JOptionPane.showConfirmDialog(this,"Thêm thành công");
             showData(list);
             writeFile();
        }
        else {
            JOptionPane.showConfirmDialog(this, "Nhập đầy đủ thông tin!");
        }
        
    }//GEN-LAST:event_jbtnthemActionPerformed
    public boolean check()
    {
        if (txtdongMay.getText().isEmpty()||txtseries.getText().isEmpty()||txtcpu.getText().isEmpty()
                ||txtram.getText().isEmpty()||txtoCung.getText().isEmpty()||txtmanHinh.getText().isEmpty()
                ||txtgia.getText().isEmpty()||txtdoPhanGiai.getText().isEmpty()||txtcardDoHoa.getText().isEmpty()||txttrongluong.getText().isEmpty())
        {
            return false;
        }
        else return true;
    }
    private void desplaydetails (int selectedRows){
        
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        displayDetails(((JTable)evt.getSource()).getSelectedRow());
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtdongMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdongMayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdongMayActionPerformed
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFrame().setVisible(true);
                   
                    
                } catch (IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

           
        });
    }
    private void jbtthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtthoatActionPerformed
        // TODO add your handling code here:
         int confirmed = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát khỏi chương trình ?", "Hộp thoạt....", JOptionPane.YES_NO_OPTION);
        if (confirmed==JOptionPane.YES_OPTION){
            writeFile();
             try {
                 writeMatkhau();
             } catch (IOException ex) {
                 Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
             }
            System.exit(0);}
       
    }//GEN-LAST:event_jbtthoatActionPerformed

    private void jbtntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntimkiemActionPerformed
        // TODO add your handling code here:
        ArrayList<Laptop> list1=new ArrayList<>();
        boolean kiemtra=false;
        for (Laptop lp:list)
        {
            
            if (lp.dongMay.contains( txtdongMay.getText())&&lp.CPU.contains( txtcpu.getText())&&lp.Gia.contains( txtgia.getText())
                &&lp.series.contains( txtseries.getText())&&lp.RAM.contains( txtram.getText())&&lp.oCung.contains( txtoCung.getText())
                &&lp.manHinh.contains( txtmanHinh.getText())&&lp.doPhanGiai.contains( txtdoPhanGiai.getText())&&lp.cardDoHoa.contains( txtcardDoHoa.getText())
                &&lp.trongLuong.contains( txttrongluong.getText())) list1.add(lp);
            
        }
        showData(list1);  
    }//GEN-LAST:event_jbtntimkiemActionPerformed

    private void showData(ArrayList<Laptop> list2)
    {
        int i=1;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (Laptop s1: list2)
        {
            model.addRow(new Object[]{
       i++,s1.getDongMay(),s1.getSeries(),s1.getCPU(),s1.getRAM(),s1.getoCung(),s1.getManHinh(),s1.getDoPhanGiai(),
           s1.getCardDoHoa(),s1.getTrongLuong(),s1.getGia()
       });
        }
        
    }
    private void jbtnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnxoaActionPerformed
        // TODO add your handling code here:
        int removeIndex=jTable1.getSelectedRow();
        if (removeIndex== -1)
        {
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn 1 Laptop để xóa!");
        }else if(list.size()==0)
        {
            JOptionPane.showMessageDialog(rootPane, "Không còn thông tin để xóa!");
        }
        else {
            list.remove(removeIndex);
            showData(list);
            writeFile();
            
        }
    }//GEN-LAST:event_jbtnxoaActionPerformed

    private void jbtnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnresetActionPerformed
        // TODO add your handling code here:
        txtcardDoHoa.setText("");
        txtcpu.setText("");
        txttrongluong.setText("");
        txtseries.setText("");
        txtram.setText("");
        txtoCung.setText("");
        txtmanHinh.setText("");
        txtgia.setText("");
        txtdongMay.setText("");
        txtdoPhanGiai.setText("");

        
    }//GEN-LAST:event_jbtnresetActionPerformed

    private void jbtnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsuaActionPerformed
        // TODO add your handling code here:
        Update();
        showData(list);
        writeFile();
    }//GEN-LAST:event_jbtnsuaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String password=String.valueOf(jPasswordField2.getPassword());
            if(password.equals(PassWord))
            {
                
                CardLayout cardLayout=(CardLayout) this.getContentPane().getLayout();
                cardLayout.next(this.getContentPane());
            }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtdoimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdoimatkhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdoimatkhauActionPerformed

    private void jbtndoimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndoimatkhauActionPerformed
        // TODO add your handling code here:
        PassWord=txtdoimatkhau.getText();
        txtdoimatkhau.setText("");
        try {
            writeMatkhau();
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtndoimatkhauActionPerformed
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Interface_Management;
    private javax.swing.JPanel Loggin;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtndoimatkhau;
    private javax.swing.JButton jbtnhienthi;
    private javax.swing.JButton jbtnreset;
    private javax.swing.JButton jbtnsua;
    private javax.swing.JButton jbtnthem;
    private javax.swing.JButton jbtntimkiem;
    private javax.swing.JButton jbtnxoa;
    private javax.swing.JButton jbtthoat;
    private javax.swing.JTextField txtcardDoHoa;
    private javax.swing.JTextField txtcpu;
    private javax.swing.JTextField txtdoPhanGiai;
    private javax.swing.JTextField txtdoimatkhau;
    private javax.swing.JTextField txtdongMay;
    private javax.swing.JTextField txtgia;
    private javax.swing.JTextField txtmanHinh;
    private javax.swing.JTextField txtoCung;
    private javax.swing.JTextField txtram;
    private javax.swing.JTextField txtseries;
    private javax.swing.JTextField txttrongluong;
    // End of variables declaration//GEN-END:variables

    private void displayDetails(int selectedRow) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    private void Update ()
    {
        int i=jTable1.getSelectedRow();
        Laptop lp=list.get(i);
        if (!txtdongMay.getText().isEmpty())
        {
            lp.dongMay=txtdongMay.getText();
        }
        if (!txtseries.getText().isEmpty())
        {
             lp.series=txtseries.getText();
        }
        if (!txtcpu.getText().isEmpty())
        {
            lp.CPU=txtcpu.getText();
        }
        if (!txtram.getText().isEmpty())
        {
            lp.RAM=txtram.getText();
        }
        if (!txtoCung.getText().isEmpty())
        {
            lp.oCung=txtoCung.getText();
        }
        if (!txtmanHinh.getText().isEmpty())
        {
            lp.manHinh=txtmanHinh.getText();
        }
        if (!txtdoPhanGiai.getText().isEmpty())
        {
            lp.doPhanGiai=txtdoPhanGiai.getText();
        }
        if (!txtcardDoHoa.getText().isEmpty())
        {
           lp.cardDoHoa=txtcardDoHoa.getText();
        }
        if (!txttrongluong.getText().isEmpty())
        {
            lp.trongLuong=txttrongluong.getText();
        }
        if (!txtgia.getText().isEmpty())
        {
            lp.Gia=txtgia.getText();
        }    
    }

    

}
